name: Update Packagist

on:
  push:
    branches: [main]
  create:
    tags:
      - 'v*'

jobs:
  packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Packagist
        run: |
          curl -s -X POST \
            "https://packagist.org/api/update-package?username=Tryortho&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}" \
            -d '{"repository":{"url":"https://github.com/Sanwohq/laravel"}}'
